#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser
from logs.log_manager import *
from beacons.server import *
from tracking.libs.videostream import *
from common.parallel import Thread


def server(args):
    LogManager().start()
    srv = SupervisorServer()

    # srv.init_tracking(camera=VideoStream.JETSONCAMERA)

    srv.run()


parser = ArgumentParser()
subparsers = parser.add_subparsers()


server_parser = subparsers.add_parser('server')
server_parser.set_defaults(func=server)


args = parser.parse_args()
args.func(args)
