// Generated by gencpp from file raspberry/tos_data.msg
// DO NOT EDIT!


#ifndef RASPBERRY_MESSAGE_TOS_DATA_H
#define RASPBERRY_MESSAGE_TOS_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raspberry
{
template <class ContainerAllocator>
struct tos_data_
{
  typedef tos_data_<ContainerAllocator> Type;

  tos_data_()
    : angle(0.0)
    , modalite(false)  {
    }
  tos_data_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , modalite(false)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _modalite_type;
  _modalite_type modalite;





  typedef boost::shared_ptr< ::raspberry::tos_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raspberry::tos_data_<ContainerAllocator> const> ConstPtr;

}; // struct tos_data_

typedef ::raspberry::tos_data_<std::allocator<void> > tos_data;

typedef boost::shared_ptr< ::raspberry::tos_data > tos_dataPtr;
typedef boost::shared_ptr< ::raspberry::tos_data const> tos_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raspberry::tos_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raspberry::tos_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raspberry::tos_data_<ContainerAllocator1> & lhs, const ::raspberry::tos_data_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.modalite == rhs.modalite;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raspberry::tos_data_<ContainerAllocator1> & lhs, const ::raspberry::tos_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raspberry

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raspberry::tos_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raspberry::tos_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspberry::tos_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raspberry::tos_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry::tos_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raspberry::tos_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raspberry::tos_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2965ddc92e8c7a12fe65f43c2825ba6";
  }

  static const char* value(const ::raspberry::tos_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2965ddc92e8c7a1ULL;
  static const uint64_t static_value2 = 0x2fe65f43c2825ba6ULL;
};

template<class ContainerAllocator>
struct DataType< ::raspberry::tos_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raspberry/tos_data";
  }

  static const char* value(const ::raspberry::tos_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raspberry::tos_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
"bool modalite\n"
;
  }

  static const char* value(const ::raspberry::tos_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raspberry::tos_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.modalite);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tos_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raspberry::tos_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raspberry::tos_data_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "modalite: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.modalite);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASPBERRY_MESSAGE_TOS_DATA_H
